language: android

android:
    components:
        - tools
        - build-tools-24.0.1
        - android-24
        - platform-tools
        - extra-android-support
        - extra-android-m2repository

jdk:
    - oraclejdk8

script:
    - ./gradlew build

before_install:
    - "chmod +x ./gradlew"
 
deploy:
  provider: releases
  api_key: "ddb231c3df73e093fc42086491c6e17fca5ccd70"
  file: "app-debug.apk"
  skip_cleanup: true
  on:
    tags: true 
