language: android

android:
    components:
        - tools
        - build-tools-24.0.1
        - android-24
        - platform-tools
        - extra-android-support
        - extra-android-m2repository

jdk:
    - oraclejdk8

script:
    - ./gradlew build

before_install:
    - "chmod +x ./gradlew"
    
deploy:
  provider: releases
  user: "ritika@promactinfo.com"
  password: "clenbee20102011"
  file: "CalculatorApp/app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on:
    branch: master
    repo: ritika05/Android
    
