language: android
jdk: oraclejdk8
android:
  components:
    # The BuildTools version used by your project
    - build-tools-19.0.0

    # The SDK version used to compile your project
    - android-19
script:
   - ./gradlew build connectedCheck
before_install:
    - chmod +x ./gradlew