language: android
jdk: oraclejdk8
android:
  components:
    # The BuildTools version used by your project
    -tools
    - build-tools-24.0.1

    # The SDK version used to compile your project
    - android-24
script:
   - ./gradlew build
before_install:
    - chmod +x ./gradlew