language: android

android:
    components:
        - tools
        - build-tools-23.0.0
        - android-23
        - platform-tools
        - extra-android-support
        - extra-android-m2repository

    jdk:
        - oraclejdk8
    script:
        - ./gradlew build
    before_install:
        - "chmod +x ./gradlew"